Repository pastelnetwork/gonode, pull requests merged in 2021-06, with the labels that each got.

#78 Detect not merged code
  .circleci/config.yml
  scripts/merge_master.sh
  walletnode/services/artworkregister/config.go
  walletnode/services/artworkregister/task.go
  walletnode/services/artworkregister/task_test.go
Labels: devops

#67 Create metadb service for supernode
  common/errors/utils.go
  common/go.mod
  common/go.sum
  common/log/debug.go
  common/log/entry.go
  common/log/exported.go
  metadb/config.go
  metadb/go.mod
  metadb/go.sum
  metadb/metadb.go
  metadb/result.go
  metadb/rqlite/auth/credential_store.go
  metadb/rqlite/auth/credential_store_test.go
  metadb/rqlite/cluster/join.go
  metadb/rqlite/cluster/join_test.go
  metadb/rqlite/cluster/service.go
  metadb/rqlite/cluster/service_mux_test.go
  metadb/rqlite/cluster/service_test.go
  metadb/rqlite/command/marshal_test.go
  metadb/rqlite/disco/client.go
  metadb/rqlite/disco/client_test.go
  metadb/rqlite/http/request_parser.go
  metadb/rqlite/http/service.go
  metadb/rqlite/http/service_test.go
  metadb/rqlite/store/errors.go
  metadb/rqlite/store/logger.go
  metadb/rqlite/store/store.go
  metadb/rqlite/store/store_test.go
  metadb/rqlite/system_test/cluster_test.go
  metadb/rqlite/system_test/helpers.go
  metadb/rqlite/system_test/single_node_test.go
  metadb/rqlite/tcp/mux.go
  metadb/rqlite/tcp/mux_test.go
  metadb/server.go
  metadb/store.go
  metadb/store_test.go
  p2p/config.go
  p2p/go.mod
  p2p/go.sum
  pastel/go.sum
  pqsignatures/go.sum
  probe/go.mod
  probe/go.sum
  supernode/.gitignore
  supernode/cmd/app.go
  supernode/configs/config.go
  supernode/configs/node.go
  supernode/examples/configs/localnet-4444.yml
  supernode/examples/configs/localnet-4445.yml
  supernode/examples/configs/localnet-4446.yml
  supernode/examples/configs/localnet-4447.yml
  supernode/examples/configs/mainnet.yml
  supernode/examples/configs/testnet.yml
  supernode/go.mod
  supernode/go.sum
  tools/pastel-api/go.sum
  walletnode/go.sum
Labels: enhancement

#84 add context.Context to function WaitForApplied
  metadb/rqlite/store/store.go
  metadb/rqlite/store/store_test.go
  metadb/server.go
Labels: enhancement

#91 Kademlia refactor
  p2p/client.go
  p2p/config.go
  p2p/go.mod
  p2p/go.sum
  p2p/kademlia/LICENSE
  p2p/kademlia/Makefile
  p2p/kademlia/README.md
  p2p/kademlia/crypto/sha3.go
  p2p/kademlia/dao/key.go
  p2p/kademlia/dao/mem/key.go
  p2p/kademlia/dao/sqlite/key.go
  p2p/kademlia/dao/sqlite/queries.go
  p2p/kademlia/dao/sqlite/queries_test.go
  p2p/kademlia/dht.go
  p2p/kademlia/dht_test.go
  p2p/kademlia/hashtable.go
  p2p/kademlia/hashtable_test.go
  p2p/kademlia/helpers/timer.go
  p2p/kademlia/message.go
  p2p/kademlia/netmsg.go
  p2p/kademlia/netmsg_test.go
  p2p/kademlia/network.go
  p2p/kademlia/networking.go
  p2p/kademlia/networking_test.go
  p2p/kademlia/node.go
  p2p/kademlia/node_test.go
  p2p/kademlia/store.go
  p2p/kademlia/store/db/db.go
  p2p/kademlia/store/mem/mem.go
  p2p/p2p.go
  supernode/examples/configs/localnet-4444.yml
  supernode/examples/configs/localnet-4445.yml
  supernode/examples/configs/localnet-4446.yml
  supernode/examples/configs/localnet-4447.yml
  supernode/examples/configs/mainnet.yml
  supernode/examples/configs/testnet.yml
  supernode/go.sum
Labels: enhancement

#93 optimize the logic for callFor function
  pastel/client.go
Labels: enhancement

#97 fix issues for unit tests
  p2p/kademlia/dht_test.go
Labels: bug
